# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from openbb_terminal.core.pb.models import api_relay_pb2 as openbb__terminal_dot_core_dot_pb_dot_models_dot_api__relay__pb2


class APIRelayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.operation_call = channel.unary_unary(
                '/openbb_terminal.core.APIRelay/operation_call',
                request_serializer=openbb__terminal_dot_core_dot_pb_dot_models_dot_api__relay__pb2.OperationCall.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Value.FromString,
                )


class APIRelayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def operation_call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIRelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'operation_call': grpc.unary_unary_rpc_method_handler(
                    servicer.operation_call,
                    request_deserializer=openbb__terminal_dot_core_dot_pb_dot_models_dot_api__relay__pb2.OperationCall.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Value.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openbb_terminal.core.APIRelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class APIRelay(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def operation_call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openbb_terminal.core.APIRelay/operation_call',
            openbb__terminal_dot_core_dot_pb_dot_models_dot_api__relay__pb2.OperationCall.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
