"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.struct_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class OperationCall(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_PATH_FIELD_NUMBER: builtins.int
    PARAMETER_MAP_FIELD_NUMBER: builtins.int
    operation_path: builtins.str
    @property
    def parameter_map(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        operation_path: builtins.str = ...,
        parameter_map: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["parameter_map", b"parameter_map"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operation_path", b"operation_path", "parameter_map", b"parameter_map"]) -> None: ...

global___OperationCall = OperationCall
