# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openbb_terminal/core/pb/models/api_relay.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.openbb_terminal/core/pb/models/api_relay.proto\x12\x14openbb_terminal.core\x1a\x1cgoogle/protobuf/struct.proto\"W\n\rOperationCall\x12\x16\n\x0eoperation_path\x18\x01 \x01(\t\x12.\n\rparameter_map\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct2[\n\x08\x41PIRelay\x12O\n\x0eoperation_call\x12#.openbb_terminal.core.OperationCall\x1a\x16.google.protobuf.Value\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openbb_terminal.core.pb.models.api_relay_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPERATIONCALL._serialized_start=102
  _OPERATIONCALL._serialized_end=189
  _APIRELAY._serialized_start=191
  _APIRELAY._serialized_end=282
# @@protoc_insertion_point(module_scope)
